# Githubs Tool for scanning my Cargo.toml land Cargo.lock to notify me if any updates or security risks are in need of adressing
version: 2
updates:
    #If my Ci is using a Version of an outdated Github Action notify me
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    # Check Cargo Dependencies
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "*"
        # patch and minor updates don't matter for libraries
        # remove this ignore rule if your package has binaries
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
